//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentManagerment.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue
    {
        public int RevenueId { get; set; }
        public Nullable<System.DateTime> RevenueStartPaymentDay { get; set; }
        public Nullable<int> RevenuePrice { get; set; }
        public Nullable<int> RevenueStudentId { get; set; }
        public Nullable<int> ExpenditureId { get; set; }
    
        public virtual Expenditure Expenditure { get; set; }
        public virtual Student Student { get; set; }
    }
}
