//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentManagerment.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleManager
    {
        public int RoleManagerId { get; set; }
        public Nullable<int> RoleManagerUserId { get; set; }
        public Nullable<int> RoleManagerRoleId { get; set; }
    }
}
